import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { MantineProvider } from "@mantine/core";
import "@mantine/charts/styles.css";
import "@mantine/core/styles.css";

import Sidebar from "../components/Sidebar/page";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <MantineProvider>
            <main className="flex gap-5 bg-back-default h-full">
                <Sidebar />

                <main className="w-full h-full">{children}</main>
            </main>
        </MantineProvider>
    );
}
